#!/bin/bash

clear

# warna
k="\e[1;33m"
h="\e[1;32m"
r="\e[0m"
w="\e[1;37m"

echo -e "${w}"
echo "+======================================================================+ "
echo "|                                                                      | "
echo "|              Program : Seting ip address statis                      | "
echo "|              Pembuat : Rofi                                          | "
echo "|              Github  : https://github.com/R0P1/SIAS.git              | "
echo "|              E-mail  : pysoft.biz@gmail.com                          | "
echo "|                                                                      | "
echo "+======================================================================+ "
echo -e "${r}"

read -p $'\e[1;37m[\e[1;32m$\e[1;37m] Masukkan Ethernet (contoh: eth0): ' e
read -p $'\e[1;37m[\e[1;32m$\e[1;37m] Masukkan alamat IP (contoh: 192.168.1.14): ' a
read -p $'\e[1;37m[\e[1;32m$\e[1;37m] Masukkan prefix alamat IP (contoh: 24): ' p
read -p $'\e[1;37m[\e[1;32m$\e[1;37m] Masukkan alamat gateway IP (contoh: 192.168.1.1): ' g
read -p $'\e[1;37m[\e[1;32m$\e[1;37m] Masukkan dns-nameservers (contoh: 8.8.8.8): ' d

# file konfigurasi 
f="/etc/netplan/01-network-manager-all.yaml"

echo ""
echo -e "${w}[${k}*${w}] ${k}Sedang melakukan konfigurasi${w}...${r}"
sleep 5

# konfigurasi 
echo "" >> $f
echo "# Seting ip address statis" >> $f
echo "# Oleh Rofi" >> $f
echo "# https://github.com/R0P1/SIAS.git" >> $f
echo "" >> $f
echo "network:" >> $f
echo "  version: 2" >> $f
echo "  renderer: networkd" >> $f
echo "  ethernets:" >> $f
echo "    $e:" >> $f
echo "      dhcp4: no" >> $f
echo "      addresses:" >> $f
echo "        - $a/$p" >> $f
echo "      gateway4: $g" >> $f
echo "      nameservers:" >> $f
echo "        addresses: [$g]" >> $f
echo "" >> $f

netplan apply > /dev/null 2>&1

echo -e "${w}[${h}+${w}] ${h}Selesai${w}.${r}"
echo ""
